# Generated by Django 5.2.8 on 2025-11-19 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientprofile",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="user",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="alcohol_drinking",
            field=models.BooleanField(
                default=False, help_text="Heavy alcohol consumption"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="bmi",
            field=models.FloatField(blank=True, help_text="Body Mass Index", null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="difficulty_walking",
            field=models.BooleanField(
                default=False, help_text="Difficulty walking/climbing stairs"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="has_asthma",
            field=models.BooleanField(default=False, help_text="Diagnosed with asthma"),
        ),
        migrations.AddField(
            model_name="user",
            name="has_kidney_disease",
            field=models.BooleanField(
                default=False, help_text="Diagnosed with kidney disease"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="has_skin_cancer",
            field=models.BooleanField(
                default=False, help_text="Diagnosed with skin cancer"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_diabetic",
            field=models.BooleanField(
                default=False, help_text="Diagnosed with diabetes"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_smoker",
            field=models.BooleanField(
                default=False, help_text="Has smoked 100+ cigarettes"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="mental_health_days",
            field=models.IntegerField(
                blank=True,
                help_text="Days of poor mental health in past 30 days",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="overall_health",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Excellent", "Excellent"),
                    ("Very Good", "Very Good"),
                    ("Good", "Good"),
                    ("Fair", "Fair"),
                    ("Poor", "Poor"),
                ],
                default="Good",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="physical_activity",
            field=models.BooleanField(
                default=True, help_text="Regular physical activity"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="physical_health_days",
            field=models.IntegerField(
                blank=True,
                help_text="Days of poor physical health in past 30 days",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="previous_stroke",
            field=models.BooleanField(default=False, help_text="Ever had a stroke"),
        ),
        migrations.AddField(
            model_name="user",
            name="race",
            field=models.CharField(
                blank=True,
                choices=[
                    ("White", "White"),
                    ("Black", "Black/African American"),
                    ("Asian", "Asian"),
                    ("Hispanic", "Hispanic/Latino"),
                    ("Native American", "Native American"),
                    ("Pacific Islander", "Pacific Islander"),
                    ("Other", "Other"),
                ],
                default="White",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female")],
                default="Male",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="sleep_hours",
            field=models.FloatField(
                blank=True, help_text="Average sleep hours per night", null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
        migrations.DeleteModel(
            name="DoctorProfile",
        ),
        migrations.DeleteModel(
            name="PatientProfile",
        ),
    ]
