# Generated by Django 5.2.8 on 2025-11-13 12:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_file', models.FileField(upload_to='blood_reports/%Y/%m/%d/')),
                ('report_type', models.CharField(choices=[('comprehensive', 'Comprehensive'), ('basic', 'Basic'), ('annual', 'Annual Checkup')], default='comprehensive', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Processing'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=20)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('processed_date', models.DateTimeField(blank=True, null=True)),
                ('ocr_extracted_data', models.JSONField(blank=True, default=dict)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicalIndicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('indicator_name', models.CharField(max_length=50)),
                ('indicator_value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('reference_range_min', models.FloatField()),
                ('reference_range_max', models.FloatField()),
                ('is_abnormal', models.BooleanField(default=False)),
                ('blood_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='reports.bloodreport')),
            ],
        ),
    ]
